### ISSUE TITLE
Document jstris compatible controls

### ISSUE THREAD

**Issue by Kos** [C010UR/ftxui-tetris#3]
For users coming from jstris or tetr.io, it would be helpful to document the compatible color scheme. Here goes:

```yaml
controls:
  moveLeft: "\x1b[D"
  moveRight: "\x1b[C"
  rotateLeft: z
  rotateRight: "\x1b[A"
  swapHold: c
  softDrop: "\x1b[B"
  hardDrop: " "
  forfeit: t
  retry: r
```

Amazing work on the project!
